config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :nutta
  root 'home#index'
  get 'home/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/nuttum.rb
class Nuttum < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def list
  end
end

app/controllers/nutta_controller.rb
class NuttaController < ApplicationController
  before_action :set_nuttum, only: %i[ show edit update destroy ]

  # GET /nutta or /nutta.json
  def index
    @nutta = Nuttum.all
  end

  # GET /nutta/1 or /nutta/1.json
  def show
  end

  # GET /nutta/new
  def new
    @nuttum = Nuttum.new
  end

  # GET /nutta/1/edit
  def edit
  end

  # POST /nutta or /nutta.json
  def create
    @nuttum = Nuttum.new(nuttum_params)

    respond_to do |format|
      if @nuttum.save
        format.html { redirect_to nuttum_url(@nuttum), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @nuttum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @nuttum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nutta/1 or /nutta/1.json
  def update
    respond_to do |format|
      if @nuttum.update(nuttum_params)
        format.html { redirect_to nuttum_url(@nuttum), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @nuttum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @nuttum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nutta/1 or /nutta/1.json
  def destroy
    @nuttum.destroy

    respond_to do |format|
      format.html { redirect_to nutta_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nuttum
      @nuttum = Nuttum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def nuttum_params
      params.require(:nuttum).permit(:Article, :title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nutta_helper.rb
module NuttaHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <%= link_to 'Home', root_path, class:"navbar-brand"%>
  
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
       
        <li class="nav-item">
            <%= link_to 'About', home_about_path, class:"nav-link"%>
        </li>

         <li class="nav-item">
            <%= link_to 'Article', new_nuttum_path, class:"nav-link"%>
        </li>

        <li class="nav-item">
            <%= link_to 'Comment', nutta_path, class:"nav-link"%>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link"%>
          </li>
        
          <li class="nav-item">
              <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link"%>
          </li>

        <% else %>
          <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link"%>
          </li>

          <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class:"nav-link"%>
          </li>
        <% end %>
        
    
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>

app/views/home/index.html.erb
<h1>Hello</h1>
<p>My name is Nuttatida Pohplook</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My HomeWork</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>

    <%= render 'home/header'%>
    <div class="container">
    </br>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

app/views/nutta/_form.html.erb
<%= form_with(model: nuttum) do |form| %>
  <% if nuttum.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(nuttum.errors.count, "error") %> prohibited this nuttum from being saved:</h2>

      <ul>
        <% nuttum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Article, style: "display: block" %>
    <%= form.text_field :Article %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <button type="submit" class:"btn btn-primary">Create comment</button>
    
  </div>
<% end %>

app/views/nutta/_nuttum.html.erb
<div id="<%= dom_id nuttum %>">
  <p>
    <strong>Article:</strong>
    <%= nuttum.Article %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= nuttum.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= nuttum.body %>
  </p>

</div>

app/views/nutta/edit.html.erb
<h1>Editing Comment</h1>

<%= render "form", nuttum: @nuttum %>

<br>

<div>
  <%= link_to "Show", @nuttum %> |
  <%= link_to "Back", nutta_path %>
</div>

app/views/nutta/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comment Here!</h1>

<div id="nutta">
  <% @nutta.each do |nuttum| %>
    <%= render nuttum %>
    <p>
      <%= link_to "Show", nuttum, class:"btn btn-light" %>
    </p>
  <% end %>
</div>

<%= link_to "New Comment", new_nuttum_path, class:"btn btn-info" %>

app/views/nutta/new.html.erb
<h1>Add a comment</h1>

<%= render "form", nuttum: @nuttum %>

<br>

<div>
  <%= link_to "Back", nutta_path, class:"btn btn-primary" %>
</div>

app/views/nutta/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @nuttum %>

<div>
  <%= link_to "Edit this comment", edit_nuttum_path(@nuttum), class:"btn btn-secondary" %> |
  <%= link_to "Back", nutta_path, class:"btn btn-secondary" %>

</br></br>
  <%= button_to "Delete", @nuttum, method: :delete,class:"btn btn-danger" %>
</div>